### PR TITLE
Parsing images from tweets added

### PR DESCRIPTION
**Pull request by Nualiian**
The lib works great, but I found that if the tweet contains an image we have no way of displaying it. In accordance with the code style, this fork adds image parsing from tweets and makes a new `{img}` handler, that can be used in templates, that spits out the URL of the image of the tweet, if there is any.

### CODE REVIEW

**Comment by QuadDepo** [comment]
Maybe check if `array_key_exists('extended_entities', $tweet)` of the tweet, otherwise it will throw index error

**Comment by jnicol** [comment]
As QuadDepo says, this will throw an error if the tweet contains no media. I think it's a good enhancement for the library though, so I'll look at implementing this feature shortly.

**Comment by QuadDepo** [comment]
Nice seeing this back alive again, happy to help :)

**Comment by Nualiian** [comment]
I could work on this PR with some more validation if you would like to, maybe?

**Comment by jnicol** [comment]
@Nualiian Sure!

In addition to the validation some things to think about are:

- Handling the different media types Twitter supports (photo, video, animated_gif)
- Displaying the media as an `` or `<video>` HTML tag below the tweet's text

**Comment by Nualiian** [comment]
@jnicol okay, that makes sense. I will look into it over the weekend

**Comment by bilalmalkoc** [comment]
Hello. Did you add media support?

**Comment by Nualiian** [comment]
@bilalmalkoc never got around to do that, no

**Pull request closed without merging**
